name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  Security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx lockfile-lint --path package-lock.json --allowed-schemes git+https: https:

  AVA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run ava -- --serial

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint